name       : mypaint-brushes1
version    : 1.3.1
release    : 1
source     :
    - https://github.com/mypaint/mypaint-brushes/releases/download/v1.3.1/mypaint-brushes-1.3.1.tar.xz : fef66ffc241b7c5cd29e9c518e933c739618cb51c4ed4d745bf648a1afc3fe70
homepage   : https://github.com/mypaint/mypaint-brushes
license    :
    - CC0-1.0
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Brushes to be used with the MyPaint library
description: |
    Brushes used by MyPaint and other software using libmypaint.
patterns   : /usr/share/pkgconfig/mypaint-brushes-1.0.pc
rundeps    :
    - libmypaint
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
